package br.com.casamagalhaes.panamah.sdk;

public enum PanamahTipoModel {
	CLIENTE, COMPRA, ASSINANTE, ACESSO, EAN, ESTOQUE_MOVIMENTACAO, EVENTO_CAIXA, FORMA_PAGAMENTO, FORNECEDOR,
	FUNCIONARIO, GRUPO, HOLDING, LOCAL_ESTOQUE, LOJA, META, PRODUTO, REVENDA, SECAO, SUBGRUPO, TITULO_PAGAR,
	TITULO_RECEBER, TROCA_DEVOLUCAO, TROCA_FORMA_PAGAMENTO, VENDA
}
